### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined 

### ISSUE THREAD

**Issue by Prazzy** [acuster25/pathlet#1]
I am getting this error. 

Fatal Error
Uncaught TypeError: Cannot read property 'prototype' of undefined (http://localhost:5601/bundles/kibana.bundle.js?v=8467:126745)

pathlet/public/lib/leaflet.markercluster.freezable-src.js

var LMCG = L.MarkerClusterGroup,
    LMCGproto = LMCG.**prototype**;

Any suggestions?

**Comment by acuster25** [comment]
The mavrkercluster-freezable plugin is not currently implemented - the file is just there while I work on it. So for now, I'd say just delete that file (as well as the reference to it in pathlet.js).
